wandb_version: 1

_n_gpu:
  desc: null
  value: 1
_name_or_path:
  desc: null
  value: monologg/koelectra-small-v3-discriminator
_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: huggingface
    huggingface_version: 4.4.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.28
      6: 4.4.1
      8:
      - 5
adafactor:
  desc: null
  value: false
adam_beta1:
  desc: null
  value: 0.9
adam_beta2:
  desc: null
  value: 0.999
adam_epsilon:
  desc: null
  value: 1.0e-08
add_cross_attention:
  desc: null
  value: false
architectures:
  desc: null
  value:
  - ElectraForPreTraining
attention_probs_dropout_prob:
  desc: null
  value: 0.1
bad_words_ids:
  desc: null
  value: null
bos_token_id:
  desc: null
  value: null
chunk_size_feed_forward:
  desc: null
  value: 0
dataloader_drop_last:
  desc: null
  value: false
dataloader_num_workers:
  desc: null
  value: 0
dataloader_pin_memory:
  desc: null
  value: true
ddp_find_unused_parameters:
  desc: null
  value: None
debug:
  desc: null
  value: false
decoder_start_token_id:
  desc: null
  value: null
deepspeed:
  desc: null
  value: None
disable_tqdm:
  desc: null
  value: false
diversity_penalty:
  desc: null
  value: 0.0
do_eval:
  desc: null
  value: None
do_predict:
  desc: null
  value: false
do_sample:
  desc: null
  value: false
do_train:
  desc: null
  value: true
early_stopping:
  desc: null
  value: false
embedding_size:
  desc: null
  value: 128
encoder_no_repeat_ngram_size:
  desc: null
  value: 0
eos_token_id:
  desc: null
  value: null
eval_accumulation_steps:
  desc: null
  value: None
eval_batch_size:
  desc: null
  value: 8
eval_steps:
  desc: null
  value: 500
evaluation_strategy:
  desc: null
  value: 'no'
finetuning_task:
  desc: null
  value: null
forced_bos_token_id:
  desc: null
  value: null
forced_eos_token_id:
  desc: null
  value: null
fp16:
  desc: null
  value: false
fp16_backend:
  desc: null
  value: auto
fp16_full_eval:
  desc: null
  value: false
fp16_opt_level:
  desc: null
  value: O1
gradient_accumulation_steps:
  desc: null
  value: 1
greater_is_better:
  desc: null
  value: None
group_by_length:
  desc: null
  value: false
hidden_act:
  desc: null
  value: gelu
hidden_dropout_prob:
  desc: null
  value: 0.1
hidden_size:
  desc: null
  value: 256
id2label:
  desc: null
  value:
    '0': LABEL_0
    '1': LABEL_1
ignore_data_skip:
  desc: null
  value: false
initializer_range:
  desc: null
  value: 0.02
intermediate_size:
  desc: null
  value: 1024
is_decoder:
  desc: null
  value: false
is_encoder_decoder:
  desc: null
  value: false
label2id:
  desc: null
  value:
    LABEL_0: 0
    LABEL_1: 1
label_names:
  desc: null
  value: None
label_smoothing_factor:
  desc: null
  value: 0.0
layer_norm_eps:
  desc: null
  value: 1.0e-12
learning_rate:
  desc: null
  value: 5.0e-05
length_penalty:
  desc: null
  value: 1.0
load_best_model_at_end:
  desc: null
  value: true
local_rank:
  desc: null
  value: -1
logging_dir:
  desc: null
  value: runs/May02_02-44-52_d4e95580dcc6
logging_first_step:
  desc: null
  value: false
logging_steps:
  desc: null
  value: 500
logging_strategy:
  desc: null
  value: steps
lr_scheduler_type:
  desc: null
  value: linear
max_grad_norm:
  desc: null
  value: 1.0
max_length:
  desc: null
  value: 20
max_position_embeddings:
  desc: null
  value: 512
max_steps:
  desc: null
  value: -1
metric_for_best_model:
  desc: null
  value: None
min_length:
  desc: null
  value: 0
model_type:
  desc: null
  value: electra
no_cuda:
  desc: null
  value: false
no_repeat_ngram_size:
  desc: null
  value: 0
num_attention_heads:
  desc: null
  value: 4
num_beam_groups:
  desc: null
  value: 1
num_beams:
  desc: null
  value: 1
num_hidden_layers:
  desc: null
  value: 12
num_return_sequences:
  desc: null
  value: 1
num_train_epochs:
  desc: null
  value: 3.0
output_attentions:
  desc: null
  value: false
output_dir:
  desc: null
  value: ../input/checkpoint/ST01_95_temp_test
output_hidden_states:
  desc: null
  value: false
output_scores:
  desc: null
  value: false
overwrite_output_dir:
  desc: null
  value: false
pad_token_id:
  desc: null
  value: 0
past_index:
  desc: null
  value: -1
per_device_eval_batch_size:
  desc: null
  value: 8
per_device_train_batch_size:
  desc: null
  value: 8
per_gpu_eval_batch_size:
  desc: null
  value: None
per_gpu_train_batch_size:
  desc: null
  value: None
position_embedding_type:
  desc: null
  value: absolute
prediction_loss_only:
  desc: null
  value: false
prefix:
  desc: null
  value: null
pruned_heads:
  desc: null
  value: {}
remove_unused_columns:
  desc: null
  value: true
repetition_penalty:
  desc: null
  value: 1.0
report_to:
  desc: null
  value: '[''wandb'']'
return_dict:
  desc: null
  value: true
return_dict_in_generate:
  desc: null
  value: false
run_name:
  desc: null
  value: ST01_95_temp_test
save_steps:
  desc: null
  value: 500
save_strategy:
  desc: null
  value: steps
save_total_limit:
  desc: null
  value: 2
seed:
  desc: null
  value: 42
sep_token_id:
  desc: null
  value: null
sharded_ddp:
  desc: null
  value: '[]'
skip_memory_metrics:
  desc: null
  value: false
summary_activation:
  desc: null
  value: gelu
summary_last_dropout:
  desc: null
  value: 0.1
summary_type:
  desc: null
  value: first
summary_use_proj:
  desc: null
  value: true
task_specific_params:
  desc: null
  value: null
temperature:
  desc: null
  value: 1.0
tie_encoder_decoder:
  desc: null
  value: false
tie_word_embeddings:
  desc: null
  value: true
tokenizer_class:
  desc: null
  value: null
top_k:
  desc: null
  value: 50
top_p:
  desc: null
  value: 1.0
torchscript:
  desc: null
  value: false
tpu_metrics_debug:
  desc: null
  value: false
tpu_num_cores:
  desc: null
  value: None
train_batch_size:
  desc: null
  value: 8
transformers_version:
  desc: null
  value: 4.4.1
type_vocab_size:
  desc: null
  value: 2
use_bfloat16:
  desc: null
  value: false
vocab_size:
  desc: null
  value: 35000
warmup_ratio:
  desc: null
  value: 0.0
warmup_steps:
  desc: null
  value: 0
weight_decay:
  desc: null
  value: 0.0
