wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.10.28
    framework: huggingface
    huggingface_version: 4.4.1
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.7.7
    t:
      1:
      - 1
      - 5
      - 11
      4: 3.7.7
      5: 0.10.28
      6: 4.4.1
      8:
      - 5
